# Makefile for Gut Microbiome Analysis Project

# Python interpreter - detect which Python to use
PYTHON := $(shell which python3 2>/dev/null || which python 2>/dev/null)
ifeq ($(PYTHON),)
    $(error Python not found. Please install Python 3.8 or higher)
endif

# Notebook files
EDA_NOTEBOOK := eda.ipynb
ALL_MODELS_NOTEBOOK := all_models_healthy_vs_disease.ipynb
FINAL_MODEL_NOTEBOOK := final_model.ipynb

# Data directories
DATA_DIR := data
RESULTS_DIR := $(DATA_DIR)/results_EDA
FIGS_DIR := $(RESULTS_DIR)/figures
TABLES_DIR := $(RESULTS_DIR)/tables
ML_FIGS_DIR := $(RESULTS_DIR)/ml_figures
ML_TABLES_DIR := $(RESULTS_DIR)/ml_tables

# Virtual environment
VENV := gut_microbiome_env
VENV_BIN := $(VENV)/bin
VENV_PYTHON := $(VENV_BIN)/python
VENV_PIP := $(VENV_PYTHON) -m pip

# Detect OS for activation script
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
    ACTIVATE := $(VENV_BIN)/activate
else ifeq ($(UNAME_S),Linux)
    ACTIVATE := $(VENV_BIN)/activate
else
    ACTIVATE := $(VENV)/Scripts/activate
endif

# Preprocessed data files (generated by EDA)
PREPROCESSED_FILES := $(TABLES_DIR)/abundance_clr.csv \
                      $(TABLES_DIR)/metadata_with_disease_groups.csv \
                      $(TABLES_DIR)/alpha_diversity.csv \
                      $(TABLES_DIR)/abundance_filtered_relative.csv

.PHONY: all help install setup run clean clean-results clean-all check-data

# Default target - shows help
help:

	@echo "  Gut Microbiome Analysis - Makefile Commands"

	@echo ""
	@echo "Setup & Installation:"
	@echo "  make all            - Complete setup and run entire pipeline"
	@echo "  make setup          - Create virtual environment and install dependencies"
	@echo "  make install        - Install/update dependencies only"
	@echo ""
	@echo "Running Analysis:"
	@echo "  make run            - Run all notebooks in correct order"
	@echo "  make run-eda        - Run only the EDA notebook (data preprocessing)"
	@echo "  make run-models     - Run both model notebooks (parallel execution)"
	@echo "  make run-all-models - Run only all_models_healthy_vs_disease.ipynb"
	@echo "  make run-final      - Run only final_model.ipynb"
	@echo ""
	@echo "Utilities:"
	@echo "  make check-data     - Verify input data files exist"
	@echo "  make clean          - Remove generated results and outputs"
	@echo "  make clean-all      - Remove everything including virtual environment"
	@echo ""


# Complete setup and run
all: setup check-data run
	@echo ""

	@echo "  Complete pipeline executed successfully!"


# Create virtual environment and install dependencies
setup: $(ACTIVATE)
	@echo "✓ Setup complete! Virtual environment created and dependencies installed."

$(ACTIVATE): requirements.txt
	@echo "Creating virtual environment '$(VENV)'..."
	@echo "Using Python: $(PYTHON)"
	@if [ ! -d "$(VENV)" ]; then \
		$(PYTHON) -m venv $(VENV) --copies || \
		$(PYTHON) -m venv $(VENV) || \
		{ echo "ERROR: Failed to create virtual environment."; \
		  echo "If using conda, try: conda create -n $(VENV) python=3.10"; \
		  exit 1; }; \
	fi
	@echo "Upgrading pip..."
	@$(VENV_PYTHON) -m pip install --upgrade pip setuptools wheel || \
		{ echo "Retrying with --no-cache-dir..."; \
		  $(VENV_PYTHON) -m pip install --no-cache-dir --upgrade pip setuptools wheel; }
	@echo "Installing dependencies..."
	@$(VENV_PIP) install -r requirements.txt
	@touch $(ACTIVATE)
	@echo "✓ Virtual environment ready!"

# Install/update dependencies (assumes venv exists)
install: $(ACTIVATE)
	@echo "Installing/updating dependencies..."
	$(VENV_PIP) install --upgrade pip
	$(VENV_PIP) install -r requirements.txt
	@echo "✓ Dependencies updated!"

# Check if required input data files exist
check-data:
	@echo "Checking for required input data files..."
	@if [ ! -f "$(DATA_DIR)/MetaCardis2020_relative_abundance.csv" ]; then \
		echo "ERROR: Missing MetaCardis2020_relative_abundance.csv in $(DATA_DIR)/"; \
		exit 1; \
	fi
	@if [ ! -f "$(DATA_DIR)/MetaCardis2020_sample_metadata.csv" ]; then \
		echo "ERROR: Missing MetaCardis2020_sample_metadata.csv in $(DATA_DIR)/"; \
		exit 1; \
	fi
	@if [ ! -f "$(DATA_DIR)/MetaCardis2020_taxa_metadata.csv" ]; then \
		echo "ERROR: Missing MetaCardis2020_taxa_metadata.csv in $(DATA_DIR)/"; \
		exit 1; \
	fi
	@echo "✓ All required data files found!"

# Create necessary output directories
$(FIGS_DIR):
	@mkdir -p $(FIGS_DIR)

$(TABLES_DIR):
	@mkdir -p $(TABLES_DIR)

$(ML_FIGS_DIR):
	@mkdir -p $(ML_FIGS_DIR)

$(ML_TABLES_DIR):
	@mkdir -p $(ML_TABLES_DIR)

# Run all notebooks in order
run: run-eda run-models
	@echo ""
	@echo "✓ All notebooks executed successfully!"

# Run EDA notebook (preprocessing step)
run-eda: $(ACTIVATE) check-data $(FIGS_DIR) $(TABLES_DIR)
	@echo ""

	@echo "  Running EDA Notebook (Data Preprocessing)..."

	$(VENV_PYTHON) -m jupyter nbconvert --to notebook --execute $(EDA_NOTEBOOK) --inplace --ExecutePreprocessor.timeout=600
	@echo "✓ EDA complete! Preprocessed data saved to $(TABLES_DIR)/"

# Run both model notebooks (they can run independently after EDA)
run-models: $(PREPROCESSED_FILES) $(ML_FIGS_DIR) $(ML_TABLES_DIR)
	@echo ""

	@echo "  Running Model Notebooks..."

	@$(MAKE) run-all-models
	@$(MAKE) run-final
	@echo "✓ All model notebooks complete!"

# Run all_models_healthy_vs_disease.ipynb
run-all-models: $(ACTIVATE) $(PREPROCESSED_FILES) $(ML_FIGS_DIR) $(ML_TABLES_DIR)
	@echo ""
	@echo "Running: all_models_healthy_vs_disease.ipynb..."
	$(VENV_PYTHON) -m jupyter nbconvert --to notebook --execute $(ALL_MODELS_NOTEBOOK) --inplace --ExecutePreprocessor.timeout=600
	@echo "✓ Model comparison complete!"

# Run final_model.ipynb
run-final: $(ACTIVATE) $(PREPROCESSED_FILES) $(ML_FIGS_DIR) $(ML_TABLES_DIR)
	@echo ""
	@echo "Running: final_model.ipynb..."
	$(VENV_PYTHON) -m jupyter nbconvert --to notebook --execute $(FINAL_MODEL_NOTEBOOK) --inplace --ExecutePreprocessor.timeout=600
	@echo "✓ Final model complete!"

# Clean generated results but keep venv and input data
clean:
	@echo "Cleaning generated results..."
	@rm -rf $(RESULTS_DIR)
	@echo "✓ Results cleaned! (Virtual environment preserved)"

# Clean only result files, not directories
clean-results:
	@echo "Cleaning result files..."
	@rm -f $(TABLES_DIR)/*.csv
	@rm -f $(FIGS_DIR)/*.png $(FIGS_DIR)/*.pdf
	@rm -f $(ML_FIGS_DIR)/*.png $(ML_FIGS_DIR)/*.pdf
	@rm -f $(ML_TABLES_DIR)/*.csv
	@echo "✓ Result files cleaned!"

# Remove everything including virtual environment
clean-all: clean
	@echo "Removing virtual environment..."
	@rm -rf $(VENV)
	@echo "✓ Complete cleanup done!"

# Convenience target for re-running analysis with fresh results
rerun: clean-results run
	@echo "✓ Analysis re-run complete!"